spring.application.name=estacionamento

# Configura��es do banco de dados MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/estacionamento?useSSL=false&serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
spring.datasource.username=isalu
spring.datasource.password=123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Configura��es do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configura��es de logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE